using System;
using System.Collections.Generic;

namespace ArmatSoftware.Code.Engine.Core.Logging;

public class LogContext : Dictionary<string, string>, IDisposable
{
    /// <summary>
    /// Optional key used to retrieve executor
    /// </summary>
    public string Key
    {
        get => this[nameof(Key)];
        set => this[nameof(Key)] = value;
    }

    /// <summary>
    /// Subject type
    /// </summary>
    public string SubjectType
    {
        get => this[nameof(SubjectType)];
        set => this[nameof(SubjectType)] = value;
    }
    
    /// <summary>
    /// Unique scoped identifier for user request. Generated by ITracer
    /// </summary>
    public string CorrelationId
    {
        get => this[nameof(CorrelationId)];
        set => this[nameof(CorrelationId)] = value;
    }

    public void Dispose()
    {
        Clear();
    }
}