<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>com.armatsoftware.code.engine.storage</PackageId>
        <LangVersion>12</LangVersion>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <Title>Armat Software Code Engine Storage</Title>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Yuri Kazarov</Authors>
        <Description>Local core Code Engine Storage package (for testing only)</Description>
        <PackageVersion>$([System.DateTime]::Now.ToString(`yy.MMdd.HHmm`))</PackageVersion>
        <Version>$([System.DateTime]::Now.ToString(`yy.MMdd.HHmm`))</Version>
        <PackageOutputPath>/tmp/.nuget</PackageOutputPath>
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>
    
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ArmatSoftware.Code.Engine.Core\ArmatSoftware.Code.Engine.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.32" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
      <PackageReference Include="NuGet.Build.Packaging" Version="0.2.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
